version: '3.9'

services:
  db:
    image: mysql:5.7
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=BlogsApi
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=baianor
      - MYSQL_PASSWORD=baianor
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 2
  redis:
    image: redis:7.0.2-alpine
    restart: always
    depends_on:
      db:
        condition: service_healthy
  test:
    image: mysql:5.7
    restart: always
    tty: true
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_ROOT_PASSWORD=tester
      - MYSQL_USER=tester
      - MYSQL_PASSWORD=testing
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 2